baseURL = "https://informedpluschoice.com/"
languageCode = "en-us"
title = "Informed + Choice"
theme = "informed-choice"

[build]
  writeStats = true

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"

[params]
  description = "Access Medicare data easily with Informed + Choice"
  vueAppURL = "https://informedpluschoice.com/app/"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Insurance Agents"
    url = "/insurance-agents/"
    weight = 2
  [[menu.main]]
    name = "ACOs"
    url = "/aco/"
    weight = 3
  [[menu.main]]
    name = "Physicians"
    url = "/physicians/"
    weight = 4
  [[menu.main]]
    name = "Pharmacists"
    url = "/pharmacists/"
    weight = 5
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 6
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 7